name: Deploy to Cloudflare pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27

      - uses: nicknovitski/nix-develop@v1

      - name: Build
        run: |
          pnpm ci
          pnpm run build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: meishi
          directory: ./dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
